package hospitalpro;

import DAO.DBConnection;
import DAO.DBConnection.PatientDAO;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.Utility.Date;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.Utility to edit this template
 */
/**
 *
 * @author HP
 */
public class admit extends javax.swing.JInternalFrame {

    private Object comboBox;

    /**
     * Creates new form admit
     */
    public admit() {
        initComponents();
        loadTableData();
        clearFields();

    }

    public void autofillPatientData(String patientId) {
        // Check if the patientId is not empty
        if (patientId.isEmpty()) {
            return;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
        cmbRoomNo1 = new javax.swing.JComboBox();
        txtPatientID = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        txtBloodGroup = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        combobox3 = new javax.swing.JComboBox<>();
        drid = new javax.swing.JComboBox<>();
        drname = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        javax.swing.JButton jButton2 = new javax.swing.JButton();
        javax.swing.JButton jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        javax.swing.JButton jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatients = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Patient Admit Info"));

        jLabel1.setText("Patient ID");

        jLabel2.setText("Patient Name");

        jLabel9.setText("Blood Group");

        jLabel11.setText("Gender");

        jLabel12.setText("Disease");

        jLabel13.setText("Admit Date");

        jLabel14.setText("Room .");

        jLabel16.setText("Doctor ID");

        jLabel17.setText("Doctor Name");

        cmbRoomNo1.setEditable(true);
        cmbRoomNo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bed no1", "Bed no2", "Bed no3", "Bed no4", "ICU Bed no1", "ICU Bed no2", "ICUBed no3", "ICU Bed no4" }));
        cmbRoomNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomNo1ActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genaral room", "ICU" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "female", "Other" }));

        txtBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-" }));

        jLabel3.setText("Bed no");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("search");
        jButton5.setPreferredSize(new java.awt.Dimension(41, 21));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5jButton2ActionPerformed(evt);
            }
        });

        combobox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cold", "flu", "allergies", "headaches", "pink eye", "ear infection", "diarrhea", "stomachache", "dengue", "malaria", "cough", "fever", "ashtma", "chickenpox", "runnynose", "gastro" }));

        drid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "011", "012" }));

        drname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr.Dhiraj Shingate", "Dr.Vishakha Shingate" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(156, 156, 156))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtPatientName)
                                .addComponent(cmbGender, 0, 222, Short.MAX_VALUE)
                                .addComponent(cmbRoomNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRoomNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(drid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton2.setText("view");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton1.setText("Admit");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 153, 153));
        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton4.setText("delet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 153, 153));
        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton6.setText("Udate");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tablePatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patien ID", "Patient Name", "Gender", "Blood Group", "Disease", "Admit date", "Room", "bedno", "Doctor ID", "Doctor Name"
            }
        ));
        tablePatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePatientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePatients);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(" patient Admit Information");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");

            String sql = "INSERT INTO admit "
                    + "(PatientID,Name, Gender, Blood_Group, Disease, Admit_Date, Room, bedno, Doctor_ID, Doctor_Name) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            pst = con.prepareStatement(sql);

            pst.setString(1, txtPatientID.getText());  // Patient ID
            pst.setString(2, txtPatientName.getText());  // Patient Name
            pst.setString(3, cmbGender.getSelectedItem().toString());  // Gender
            pst.setString(4, txtBloodGroup.getSelectedItem().toString());  // Blood Group
            pst.setString(5, combobox3.getSelectedItem().toString());   // Disease
            pst.setDate(6, new java.sql.Date(jDateChooser1.getDate().getTime())); // Admit Date
            pst.setString(7, jComboBox5.getSelectedItem().toString());  // Room
            pst.setString(8, cmbRoomNo1.getSelectedItem().toString());  // Bed No
             pst.setString(9, drid.getSelectedItem().toString());  // Room
            pst.setString(10, drname.getSelectedItem().toString()); 

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Add Patient successful!");
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);

        } finally {
            // Close resources in a finally block to ensure they are always closed
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
            }
        }
        //validation for not leave blank data
        if (txtPatientID.getText().equals("") || txtPatientName.getText().equals("") || cmbGender.getSelectedItem().toString().equals("") || txtBloodGroup.getSelectedItem().toString().equals("") || combobox3.getSelectedItem().toString().equals("") || new java.sql.Date(jDateChooser1.getDate().getTime()).equals("") || jComboBox5.getSelectedItem().toString().equals("") || cmbRoomNo1.getSelectedItem().toString().equals("")|| drid.getSelectedItem().toString().equals("") || drname.getSelectedItem().toString().equals("") ) {
            // if any of three field left blank than show message
            JOptionPane.showMessageDialog(this, "Please Enter All Data !!");
        } else {
            // if all data field than...
            // store enter data into String array-data
            String data[] = {txtPatientID.getText(), txtPatientName.getText(), cmbGender.getSelectedItem().toString(), txtBloodGroup.getSelectedItem().toString(), combobox3.getSelectedItem().toString(), jComboBox5.getSelectedItem().toString(), cmbRoomNo1.getSelectedItem().toString(),  drid.getSelectedItem().toString(),  drname.getSelectedItem().toString()};

            DefaultTableModel tblModel = (DefaultTableModel) tablePatients.getModel();
            // add string array data
            tblModel.addRow(data); // row added
            // successfully added message
            JOptionPane.showMessageDialog(this, "Add Patient Data Successfully..!!");

            // clear textfield for new entry..
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        try {
            // 1️⃣ Connect to your database
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM admit";   // your table name
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            // 2️⃣ Create a table model to hold the data
            DefaultTableModel model = new DefaultTableModel();

            // 3️⃣ Add column headers (match with your DB table)
            model.addColumn("PatientID");
            model.addColumn("Name");
            model.addColumn("Gender");
            model.addColumn("Blood_Group");
            model.addColumn("Disease");
            model.addColumn("Admit_Date");
            model.addColumn("Room");
            model.addColumn("bedno");
            model.addColumn("Doctor_ID");
            model.addColumn("Doctor_Name");

            // 4️⃣ Fill rows from database
            while (rs.next()) {
                Object[] row = new Object[10];
                row[0] = rs.getString("PatientID");
                row[1] = rs.getString("Name");
                row[2] = rs.getString("Gender");
                row[3] = rs.getString("Blood_Group");
                row[4] = rs.getString("Disease");
                row[5] = rs.getDate("Admit_Date");
                row[6] = rs.getString("Room");
                row[7] = rs.getString("bedno");
                row[8] = rs.getString("Doctor_ID");
                row[9] = rs.getString("Doctor_Name");

                model.addRow(row);
            }

            // 5️⃣ Set data into JTable
            tablePatients.setModel(model);

            // 6️⃣ Close resources
            rs.close();
            pst.close();
            con.close();

            JOptionPane.showMessageDialog(this, "All patient records loaded successfully!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching data: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtPatientID.setText("");
        txtPatientName.setText("");
        cmbGender.setSelectedItem("");
        txtBloodGroup.setSelectedItem("");
        combobox3.setSelectedItem("");
        drname.setSelectedItem("");
        jDateChooser1.getDate().getTime();
        drid.setSelectedItem("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseClicked

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        //action perform ...
        //get selected values from combobox
        String selectedValue = jComboBox5.getSelectedItem().toString();
        //now srt this selected value ino text file.
        jTextField7.setText(selectedValue);

    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void cmbRoomNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomNo1ActionPerformed
        // TODO add your handling code here:
        String selectedValue = cmbRoomNo1.getSelectedItem().toString();
        //now srt this selected value ino text file.
        jTextField8.setText(selectedValue);
    }//GEN-LAST:event_cmbRoomNo1ActionPerformed

    private void jButton5jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5jButton2ActionPerformed

        try {
            // 1️⃣ Get entered Patient ID
            String patientID = txtPatientID.getText().trim();

            if (patientID.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Patient ID");
                return;
            }

            // 2️⃣ Database Connection
            Connection con = DBConnection.getConnection(); // use your connection class
            String sql = "SELECT * FROM patient WHERE PatientID = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, patientID);

            // 3️⃣ Execute Query
            ResultSet rs = pst.executeQuery();

            // 4️⃣ If patient found → set values to textfields
            if (rs.next()) {
                txtPatientName.setText(rs.getString("PatientName"));
                cmbGender.setSelectedItem(rs.getString("Gender"));
                txtBloodGroup.setSelectedItem(rs.getString("BloodGroup"));
                combobox3.setSelectedItem(rs.getString("Diagnosis"));
                  drid.setSelectedItem(rs.getString("DrID"));
                  drname.setSelectedItem(rs.getString("DrName"));

            } else {
                JOptionPane.showMessageDialog(this, "No record found for PatientID: " + patientID);
            }

            // 5️⃣ Close connection
            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton5jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel table = (DefaultTableModel) tablePatients.getModel();
        int selectedRow = tablePatients.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete!");
            return;
        }

        if (tablePatients.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Empty table data!");
            return;
        }

        // Assuming Patient ID is in the first column (index 0)
        int PatientId = Integer.parseInt(tablePatients.getValueAt(selectedRow, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete PatientID " + PatientId + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // call delete function from DAO
            boolean deleted = PatientDAO.deletePatientById(PatientId);

            if (deleted) {
                table.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Successfully removed data.");
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed. Check your DB connection.");
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void tablePatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePatientsMouseClicked
        // TODO add your handling code here:
        try {
            // Get selected row index
            int row = tablePatients.getSelectedRow();

            // Get patient ID from the first column (adjust index if needed)
            String patientID = tablePatients.getModel().getValueAt(row, 0).toString();

            // Connect to database
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM admit WHERE PatientID = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, patientID);
            ResultSet rs = pst.executeQuery();

            // Fill the form fields 
            if (rs.next()) {
                txtPatientID.setText(rs.getString("PatientID"));
                txtPatientName.setText(rs.getString("Name"));
                cmbGender.setSelectedItem(rs.getString("Gender"));
                txtBloodGroup.setSelectedItem(rs.getString("Blood_Group"));
                combobox3.setSelectedItem(rs.getString("Disease"));
                jDateChooser1.setDate(rs.getDate("Admit_Date"));
                jComboBox5.setSelectedItem(rs.getString("Room"));
                cmbRoomNo1.setSelectedItem(rs.getString("bedno"));
               drid.setSelectedItem(rs.getString("Doctor_ID"));
                drname.setSelectedItem(rs.getString("Doctor_Name"));

            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching row data: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_tablePatientsMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    try {
    // Get all field values from your form
    String patientID = txtPatientID.getText().trim();
    String Name = txtPatientName.getText().trim();
    String gender = cmbGender.getSelectedItem().toString();
    String bloodGroup = txtBloodGroup.getSelectedItem().toString();
    String ward = combobox3.getSelectedItem().toString();

    // ✅ Get date safely without imports
    java.util.Date utilDate = jDateChooser1.getDate();
    if (utilDate == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select an Admit Date!");
        return;
    }

    // ✅ Convert util.Date to sql.Date
    java.sql.Date sqlAdmitDate = new java.sql.Date(utilDate.getTime());

    String Room = jComboBox5.getSelectedItem().toString();
    String bedno = cmbRoomNo1.getSelectedItem().toString();
    String doctorID = drid.getSelectedItem().toString();
    String doctorName = drname.getSelectedItem().toString();

    // ✅ Validation example
    if (patientID.equals("") || Name.equals("")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please select a record to update!");
        return;
    }

    // ✅ Example of saving or updating
    java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
    java.sql.PreparedStatement pst = con.prepareStatement(
        "INSERT INTO admit (PatientID, Name, Gender, Blood_Group, Disease, Admit_Date, Room, bedno, Doctor_ID, Doctor_Name) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
    );

    pst.setString(1, patientID);
    pst.setString(2, Name);
    pst.setString(3, gender);
    pst.setString(4, bloodGroup);
    pst.setString(5, ward);
    pst.setDate(6, sqlAdmitDate);
    pst.setString(7, Room);
    pst.setString(8, bedno);
    pst.setString(9, doctorID);
    pst.setString(10, doctorName);

    pst.executeUpdate();
    javax.swing.JOptionPane.showMessageDialog(this, "Admit record saved successfully!");

} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
} catch (Exception e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
}




    }//GEN-LAST:event_jButton6ActionPerformed

    private void loadTableData() {
        try {
            // 1️⃣ Connect to Database
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM admit";   // change table name if needed
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            // 2️⃣ Create a table model
            DefaultTableModel model = new DefaultTableModel();

            // 3️⃣ Add column names (use your actual database column names)
            model.addColumn("PatientID");
            model.addColumn("Name");
            model.addColumn("Gender");
            model.addColumn("Blood_Group");
            model.addColumn("Disease");
            model.addColumn("Admit_Date");
            model.addColumn("Room");
            model.addColumn("Doctor_ID");
            model.addColumn("Doctor_Name");

            // 4️⃣ Add rows from ResultSet
            while (rs.next()) {
                Object[] row = new Object[10];
                row[0] = rs.getString("PatientID");
                row[1] = rs.getString("Name");
                row[2] = rs.getString("Gender");
                row[3] = rs.getString("Blood_Group");
                row[4] = rs.getString("Disease");
                row[5] = rs.getDate("Admit_Date");
                row[6] = rs.getString("Room");
                row[7] = rs.getString("Doctor_ID");
                row[8] = rs.getString("Doctor_Name");

                model.addRow(row);
            }

            // 5️⃣ Set the model to JTable
            tablePatients.setModel(model);

            // 6️⃣ Close connections
            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading table: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void clearFields() {
        txtPatientID.setText("");
        txtPatientName.setText("");
        cmbGender.setSelectedIndex(0);
        txtBloodGroup.setSelectedIndex(0);
        combobox3.setSelectedIndex(0);
        jDateChooser1.setDate(null);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox cmbRoomNo1;
    private javax.swing.JComboBox<String> combobox3;
    private javax.swing.JComboBox<String> drid;
    private javax.swing.JComboBox<String> drname;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tablePatients;
    private javax.swing.JComboBox<String> txtBloodGroup;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
