package hospitalpro;

import DAO.DBConnection;
import DAO.DBConnection.PatientDAO;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
/**
 *
 * @author DELL
 */
public class discharge extends javax.swing.JInternalFrame {

    /**
     * Creates new form discharge
     */
    public discharge() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        txtPatientID = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        cmbRoomNo1 = new javax.swing.JComboBox();
        jTextField8 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        txtBloodGroup = new javax.swing.JComboBox<>();
        jLabel76 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton5 = new javax.swing.JButton();
        combobox3 = new javax.swing.JComboBox<>();
        drid = new javax.swing.JComboBox<>();
        drname = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePatients = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        javax.swing.JButton jButton12 = new javax.swing.JButton();
        javax.swing.JButton jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        javax.swing.JButton jButton16 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Discharge Date");

        jLabel71.setText("Disease");

        jLabel17.setText("Patient ID");

        jLabel72.setText("Admit Date");

        jLabel73.setText("Room No.");

        jLabel74.setText("Doctor ID");

        jLabel75.setText("Doctor Name");

        jLabel18.setText("Patient Name");

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        jComboBox5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Genaral room", "ICU" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        cmbRoomNo1.setEditable(true);
        cmbRoomNo1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bed no1", "Bed no2", "Bed no3", "Bed no4", "ICU Bed no1", "ICU Bed no2", "ICUBed no3", "ICU Bed no4" }));
        cmbRoomNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoomNo1ActionPerformed(evt);
            }
        });

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        jLabel11.setText("Gender");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "female", "Other" }));

        jLabel9.setText("Blood Group");

        txtBloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-" }));

        jLabel76.setText("bedno");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton5.setText("search");
        jButton5.setPreferredSize(new java.awt.Dimension(41, 21));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5jButton2ActionPerformed(evt);
            }
        });

        combobox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cold", "flu", "allergies", "headaches", "pink eye", "ear infection", "diarrhea", "stomachache", "dengue", "malaria", "cough", "fever", "ashtma", "chickenpox", "runnynose", "gastro" }));

        drid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "011", "012" }));

        drname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr.Dhiraj Shingate", "Dr.Miss Shingate" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel72)
                            .addComponent(jLabel71)
                            .addComponent(jLabel73)
                            .addComponent(jLabel75)
                            .addComponent(jLabel19)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel76))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBloodGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(drid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(drname, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbRoomNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combobox3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPatientName)))
                    .addComponent(jLabel74))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBloodGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(combobox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel72)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel73)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel74)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbRoomNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(drname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Discharge Information");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(443, 443, 443)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(684, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablePatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patien ID", "Patient Name", "Gender", "Blood Group", "Disease", "Admit  date", "Room", "Bed no", "Doctor ID", "Doctor Name", "Discharge date"
            }
        ));
        tablePatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablePatientsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablePatients);

        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton12.setBackground(new java.awt.Color(0, 153, 153));
        jButton12.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton12.setText("view");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(0, 153, 153));
        jButton13.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton13.setText("Discharge");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(new java.awt.Color(0, 153, 153));
        jButton14.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton14.setText("delet");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(0, 153, 153));
        jButton15.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton15.setText("Udate");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 153, 153));
        jButton16.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 10)); // NOI18N
        jButton16.setText("Clear");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
        //action perform ...
        //get selected values from combobox
        String selectedValue = jComboBox5.getSelectedItem().toString();
        //now srt this selected value ino text file.
        jTextField7.setText(selectedValue);
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void cmbRoomNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoomNo1ActionPerformed
        // TODO add your handling code here:
        String selectedValue = cmbRoomNo1.getSelectedItem().toString();
        //now srt this selected value ino text file.
        jTextField8.setText(selectedValue);
    }//GEN-LAST:event_cmbRoomNo1ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton5jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5jButton2ActionPerformed

        try {
            // 1️⃣ Get entered Patient ID
            String patientID = txtPatientID.getText().trim();

            if (patientID.equals("")) {
                JOptionPane.showMessageDialog(this, "Please enter Patient ID");
                return;
            }

            // 2️⃣ Database Connection
            Connection con = DBConnection.getConnection(); // use your connection class
            String sql = "SELECT * FROM admit WHERE PatientID = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, patientID);

            // 3️⃣ Execute Query
            java.sql.ResultSet rs = pst.executeQuery();

            // 4️⃣ If patient found → set values to textfields
            if (rs.next()) {
                txtPatientName.setText(rs.getString("Name"));
                jDateChooser2.setDate(rs.getDate("Admit_Date"));
                txtBloodGroup.setSelectedItem(rs.getString("Blood_Group"));
                cmbGender.setSelectedItem(rs.getString("Gender"));
                combobox3.setSelectedItem(rs.getString("Disease"));
                cmbRoomNo1.setSelectedItem(rs.getString("bedno"));
                jComboBox5.setSelectedItem(rs.getString("Room"));
                drid.setSelectedItem(rs.getString("Doctor_ID"));
                drname.setSelectedItem(rs.getString("Doctor_Name"));

            } else {
                JOptionPane.showMessageDialog(this, "No record found for PatientID: " + patientID);
            }

            // 5️⃣ Close connection
            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton5jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:

        try {
            // 1️⃣ Connect to your database
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM discharge";   // your table name
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            // 2️⃣ Create a table model to hold the data
            DefaultTableModel model = new DefaultTableModel();

            // 3️⃣ Add column headers (match with your DB table)
            model.addColumn("PatientID");
            model.addColumn("Name");

            model.addColumn("Blood_Group");
            model.addColumn("Disease");
            model.addColumn("AdmitDate");
            model.addColumn("Room");
            model.addColumn("bedno");
            model.addColumn("DoctorID");
            model.addColumn("DoctorName");
            model.addColumn("Dischargedate");

            // 4️⃣ Fill rows from database
            while (rs.next()) {
                Object[] row = new Object[10];
                row[0] = rs.getString("PatientID");
                row[1] = rs.getString("Name");
                row[2] = rs.getString("Blood_Group");
                row[3] = rs.getString("Disease");
                row[4] = rs.getDate("AdmitDate");
                row[5] = rs.getString("Room");
                row[6] = rs.getString("bedno");
                row[7] = rs.getString("DoctorID");
                row[8] = rs.getString("DoctorName");
                row[9] = rs.getString("DischargeDate");

                model.addRow(row);
            }

            // 5️⃣ Set data into JTable
            tablePatients.setModel(model);

            // 6️⃣ Close resources
            rs.close();
            pst.close();
            con.close();

            JOptionPane.showMessageDialog(this, "All patient records loaded successfully!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching data: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        java.sql.PreparedStatement pst = null;
        java.sql.ResultSet rs = null;

        try {
            con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");

            String sql = "INSERT INTO discharge "
                    + "(PatientID, Name, Blood_Group, Disease, AdmitDate, Room, bedno, DoctorID, DoctorName, Dischargedate) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            pst = con.prepareStatement(sql);

            pst.setString(1, txtPatientID.getText());  // Patient ID
            pst.setString(2, txtPatientName.getText());  // Patient Name

            // Gender
            pst.setString(3, txtBloodGroup.getSelectedItem().toString());  // Blood Group
            pst.setString(4, combobox3.getSelectedItem().toString());   // Disease
            pst.setDate(5, new java.sql.Date(jDateChooser2.getDate().getTime())); // Admit Date
            pst.setString(6, jComboBox5.getSelectedItem().toString());  // Room
            pst.setString(7, cmbRoomNo1.getSelectedItem().toString());  // Bed No
            pst.setString(8, drid.getSelectedItem().toString());  // Room
            pst.setString(9, drname.getSelectedItem().toString());
            pst.setDate(10, new java.sql.Date(jDateChooser1.getDate().getTime())); // Admit Date

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "discharge Patient successful!");
        } catch (HeadlessException | java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(null, "Database Error: " + ex.getMessage(), " Error", JOptionPane.ERROR_MESSAGE);

        } finally {
            // Close resources in a finally block to ensure they are always closed
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (java.sql.SQLException ex) {
            }
        }
        //validation for not leave blank data
        if (txtPatientID.getText().equals("") || txtPatientName.getText().equals("") || txtBloodGroup.getSelectedItem().toString().equals("") || combobox3.getSelectedItem().toString().equals("") || new java.sql.Date(jDateChooser1.getDate().getTime()).equals("") || jComboBox5.getSelectedItem().toString().equals("") || cmbRoomNo1.getSelectedItem().toString().equals("") || drid.getSelectedItem().toString().equals("") || drname.getSelectedItem().toString().equals("") || new java.sql.Date(jDateChooser1.getDate().getTime()).equals("")) {
            // if any of three field left blank than show message
            JOptionPane.showMessageDialog(this, "Please Enter All Data !!");
        } else {
            // if all data field than...
            // store enter data into String array-data
            String data[] = {txtPatientID.getText(), txtPatientName.getText(), txtBloodGroup.getSelectedItem().toString(), combobox3.getSelectedItem().toString(), jComboBox5.getSelectedItem().toString(), cmbRoomNo1.getSelectedItem().toString(), drid.getSelectedItem().toString(), drname.getSelectedItem().toString()};

            DefaultTableModel tblModel = (DefaultTableModel) tablePatients.getModel();
            // add string array data
            tblModel.addRow(data); // row added
            // successfully added message
            JOptionPane.showMessageDialog(this, "Add Patient Data Successfully..!!");

            // clear textfield for new entry..
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:

        DefaultTableModel table = (DefaultTableModel) tablePatients.getModel();
        int selectedRow = tablePatients.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete!");
            return;
        }

        if (tablePatients.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Empty table data!");
            return;
        }

        // Assuming Patient ID is in the first column (index 0)
        int PatientId = Integer.parseInt(tablePatients.getValueAt(selectedRow, 0).toString());

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete PatientID " + PatientId + "?",
                "Confirm Delete", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // call delete function from DAO
            boolean deleted = PatientDAO.deletePatientById(PatientId);

            if (deleted) {
                table.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Successfully removed data.");
            } else {
                JOptionPane.showMessageDialog(this, "Delete failed. Check your DB connection.");
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        try {
            // Get all field values from your form
            String patientID = txtPatientID.getText().trim();
            String Name = txtPatientName.getText().trim();
            String bloodGroup = txtBloodGroup.getSelectedItem().toString();
            String ward = combobox3.getSelectedItem().toString();

            // ✅ Get date safely without imports
            java.util.Date utilDate = jDateChooser1.getDate();
            if (utilDate == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select an Admit Date!");
                return;
            }

            // ✅ Convert util.Date to sql.Date
            java.sql.Date sqlAdmitDate = new java.sql.Date(utilDate.getTime());
            java.sql.Date sqlDischargeDate = new java.sql.Date(utilDate.getTime());
            String Room = jComboBox5.getSelectedItem().toString();
            String bedno = cmbRoomNo1.getSelectedItem().toString();
            String doctorID = drid.getSelectedItem().toString();
            String doctorName = drname.getSelectedItem().toString();

            // ✅ Validation example
            if (patientID.equals("") || Name.equals("")) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please select a record to update!");
                return;
            }

            // ✅ Example of saving or updating
            java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/hospital", "root", "");
            java.sql.PreparedStatement pst = con.prepareStatement(
                    "INSERT INTO discharge (PatientID, Name, Blood_Group, Disease, AdmitDate, Room, bedno, DoctorID, DoctorName, DischargeDate) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)"
            );

            pst.setString(1, patientID);
            pst.setString(2, Name);
            pst.setString(3, bloodGroup);
            pst.setString(4, ward);
            pst.setDate(5, sqlAdmitDate);
            pst.setDate(6, sqlDischargeDate);
            pst.setString(7, Room);
            pst.setString(8, bedno);
            pst.setString(9, doctorID);
            pst.setString(10, doctorName);

            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Admit record saved successfully!");

        } catch (java.sql.SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        txtPatientID.setText("");
        txtPatientName.setText("");
        cmbGender.setSelectedItem("");
        txtBloodGroup.setSelectedItem("");
        combobox3.setSelectedItem("");
        drname.setSelectedItem("");
        jDateChooser1.getDate().getTime();
        drid.setSelectedItem("");
    }//GEN-LAST:event_jButton16ActionPerformed

    private void tablePatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablePatientsMouseClicked
        // TODO add your handling code here:
        try {
            // Get selected row index
            int row = tablePatients.getSelectedRow();

            // Get patient ID from the first column (adjust index if needed)
            String patientID = tablePatients.getModel().getValueAt(row, 0).toString();

            // Connect to database
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM discharge WHERE PatientID = ?";
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, patientID);
            java.sql.ResultSet rs = pst.executeQuery();

            // Fill the form fields 
            if (rs.next()) {
                txtPatientID.setText(rs.getString("PatientID"));
                txtPatientName.setText(rs.getString("Name"));

                txtBloodGroup.setSelectedItem(rs.getString("Blood_Group"));
                combobox3.setSelectedItem(rs.getString("Disease"));
                jDateChooser2.setDate(rs.getDate("AdmitDate"));
                jComboBox5.setSelectedItem(rs.getString("Room"));
                cmbRoomNo1.setSelectedItem(rs.getString("bedno"));
                drid.setSelectedItem(rs.getString("DoctorID"));
                drname.setSelectedItem(rs.getString("DoctorName"));
                jDateChooser1.setDate(rs.getDate("DischargeDate"));

            }

            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error fetching row data: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_tablePatientsMouseClicked

    private void loadTableData() {
        try {
            // 1️⃣ Connect to Database
            Connection con = DBConnection.getConnection();
            String sql = "SELECT * FROM discharge";   // change table name if needed
            java.sql.PreparedStatement pst = con.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery();

            // 2️⃣ Create a table model
            DefaultTableModel model = new DefaultTableModel();

            // 3️⃣ Add column names (use your actual database column names)
            model.addColumn("PatientID");
            model.addColumn("Name");
            model.addColumn("Gender");
            model.addColumn("Blood_Group");
            model.addColumn("Disease");
            model.addColumn("AdmitDate");
            model.addColumn("Room");
            model.addColumn("DoctorID");
            model.addColumn("DoctorName");

            // 4️⃣ Add rows from ResultSet
            while (rs.next()) {
                Object[] row = new Object[10];
                row[0] = rs.getString("PatientID");
                row[1] = rs.getString("Name");
                row[2] = rs.getString("Gender");
                row[3] = rs.getString("Blood_Group");
                row[4] = rs.getString("Disease");
                row[5] = rs.getDate("AdmitDate");
                row[6] = rs.getString("Room");
                row[7] = rs.getString("DoctorID");
                row[8] = rs.getString("DoctorName");

                model.addRow(row);
            }

            // 5️⃣ Set the model to JTable
            tablePatients.setModel(model);

            // 6️⃣ Close connections
            rs.close();
            pst.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading table: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private void clearFields() {
        txtPatientID.setText("");
        txtPatientName.setText("");
        cmbGender.setSelectedIndex(0);
        txtBloodGroup.setSelectedIndex(0);
        combobox3.setSelectedIndex(0);
        jDateChooser1.setDate(null);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox cmbRoomNo1;
    private javax.swing.JComboBox<String> combobox3;
    private javax.swing.JComboBox<String> drid;
    private javax.swing.JComboBox<String> drname;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tablePatients;
    private javax.swing.JComboBox<String> txtBloodGroup;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables

    private static class PreparedStatement {

        public PreparedStatement() {
        }

        private void executeUpdate() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void close() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void setString(int i, String text) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private ResultSet executeQuery() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private void setDate(int i, Date date) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

    private static class ResultSet {

        public ResultSet() {
        }

        private void close() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private boolean next() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private String getString(String patientName) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private Object getDate(String admit_Date) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }

    private static class SQLException {

        public SQLException() {
        }

        private String getMessage() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
}
